import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs"
import { join, resolve } from "path"
import parser from "@solidity-parser/parser"

const FILE_WITH_ENTRY_CONSTANTS = "LedgerEntries.sol"
const FILE_WITH_ACCOUNT_CONSTANTS = "Accounts.sol"

interface EntryConstant {
  name: string
  value: number
}

function findSolidityFiles(dir: string): string[] {
  const files: string[] = []
  const entries = readdirSync(dir, { withFileTypes: true })
  for (const entry of entries) {
    const fullPath = join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...findSolidityFiles(fullPath))
    } else if (entry.name.endsWith(".sol")) {
      files.push(fullPath)
    }
  }
  return files
}

function extractEnums(ast: ReturnType<typeof parser.parse>): { name: string; members: string[] }[] {
  const enums: { name: string; members: string[] }[] = []
  parser.visit(ast, {
    EnumDefinition: (node: { name: string; members: ({ name: string } | string)[] }) => {
      enums.push({
        name: node.name,
        members: node.members.map((m) => (typeof m === "string" ? m : m.name)),
      })
    },
  })
  return enums
}

function extractPrefixedConstants(ast: ReturnType<typeof parser.parse>, prefix: string): EntryConstant[] {
  const constants: EntryConstant[] = []
  parser.visit(ast, {
    FileLevelConstant: (node) => {
      if (typeof node.name !== "string" || !node.name.startsWith(prefix)) return
      const initialValue = node.initialValue as { type: string; number?: string } | undefined
      if (!initialValue || initialValue.type !== "NumberLiteral" || typeof initialValue.number !== "string") return
      constants.push({ name: node.name, value: Number.parseInt(initialValue.number, 10) })
    },
  })
  constants.sort((a, b) => a.value - b.value)
  return constants
}

function generateConstantsCode(name: string, constants: EntryConstant[]): string {
  return `
export const ${name} = {
  ${constants.map((c) => `${c.name}: ${c.value}`).join(",\n  ")}
} as const;

export type ${name} = (typeof ${name})[keyof typeof ${name}];

export function get${name}Label(value: number): string | undefined {
  const entry = Object.entries(${name}).find(([, v]) => v === value);
  return entry?.[0];
}
`
}

function generateEnumCode(name: string, members: string[]): string {
  return `
export const ${name}Values = {
  ${members.map((m, i) => `"${m}": ${i}`).join(",\n  ")}
};

export enum ${name} {
  ${members.map((m, i) => `${m} = ${i},`).join("\n  ")}
}

export function get${name}(value: bigint): ${name} | undefined {
  const num = Number(value);
  if (num >= 0 && num < ${members.length}) {
    return num as ${name};
  }
  return undefined;
}

export function get${name}Value(enumValue: ${name}): bigint {
  return BigInt(enumValue);
}`
}

export function runExtractEnums(root: string): void {
  const sourceDir = resolve(root, "contracts")
  if (!existsSync(sourceDir)) {
    throw new Error(`Directory not found: ${sourceDir}. Run "pnpm prepare:submodules" first.`)
  }
  const solidityFiles = findSolidityFiles(sourceDir)
  const allEnums: { name: string; members: string[]; file: string }[] = []
  const allEntryConstants: EntryConstant[] = []
  const allAccountConstants: EntryConstant[] = []

  for (const filePath of solidityFiles) {
    try {
      const code = readFileSync(filePath, "utf8")
      const ast = parser.parse(code, { loc: true, range: true })
      const enums = extractEnums(ast)
      allEnums.push(...enums.map((e) => ({ ...e, file: filePath })))
      if (filePath.includes(FILE_WITH_ENTRY_CONSTANTS)) {
        allEntryConstants.push(...extractPrefixedConstants(ast, "ENTRY_"))
      }
      if (filePath.includes(FILE_WITH_ACCOUNT_CONSTANTS)) {
        allAccountConstants.push(...extractPrefixedConstants(ast, "ACC_"))
      }
    } catch (error) {
      console.error(`Error parsing ${filePath}: ${(error as Error).message}`)
    }
  }

  if (allEntryConstants.length === 0) throw new Error("No ENTRY_* constants found")
  if (allAccountConstants.length === 0) throw new Error("No ACC_* constants found")
  if (allEnums.length === 0) {
    console.log("No enums found in the source files.")
    return
  }

  let tsCode = `
// Auto-generated file. Do not edit manually.
// Generated by cli (extract-enums)\n`
  allEnums.forEach(({ name, members }) => (tsCode += generateEnumCode(name, members)))
  const entryMembers = allEntryConstants.map((c) => c.name.replace("ENTRY_", ""))
  tsCode += generateEnumCode("EntryType", entryMembers)
  tsCode += generateConstantsCode("Account", allAccountConstants)

  const outputPath = resolve(root, "src/enums.ts")
  writeFileSync(outputPath, tsCode)

  console.log(`Found ${allEnums.length} enum(s)`)
  console.log(`Found ${allEntryConstants.length} ENTRY_* constant(s) -> EntryType enum`)
  console.log(`Found ${allAccountConstants.length} ACC_* constant(s) -> Account constants`)
  console.log(`TypeScript definitions written to: ${outputPath}`)
  console.log(`\nEnums found: `)
  allEnums.forEach((e) => console.log(`  - ${e.name} (${e.members.length} members)`))
  console.log(`  - EntryType (${allEntryConstants.length} members from ENTRY_* constants)`)
  console.log(`  - Account (${allAccountConstants.length} constants from ACC_*)`)
}
