import { readFileSync, writeFileSync, existsSync } from "fs"
import { join, resolve } from "path"
import { deploymentConfigs } from "./deployment-configs.js"

interface DeploymentJson {
  version: string
  commitHash: string
  component: string
  deploymentName: string
  chain: string
  chainId: number
  blockNumber: number
  timestamp: number
  contracts: Record<string, string>
}

function addr(value: string | undefined): string {
  return value ? `'${value}'` : "null"
}

export function runGenerateDeployments(root: string): void {
  const deploymentsDir = resolve(root, "deployments")

  const entries: string[] = []
  const chainOverrides: string[] = []
  const usedChains = new Set<string>()
  const found: string[] = []

  for (const [name, config] of Object.entries(deploymentConfigs)) {
    const loansPath = join(deploymentsDir, config.chain, config.shortName, "loans", "latest.json")
    const accountsPath = join(deploymentsDir, config.chain, config.shortName, "accounts", "latest.json")
    const vaultPath = join(deploymentsDir, config.chain, config.shortName, "vault", "latest.json")

    const missingManifests = [
      ["loans", loansPath],
      ["accounts", accountsPath],
      ["vault", vaultPath],
    ].filter(([, p]) => !existsSync(p)).map(([name]) => name)

    if (missingManifests.length > 0) {
      console.warn(`Skipping ${name}: missing ${missingManifests.join(", ")} deployment(s)`)
      continue
    }

    const loans: DeploymentJson = JSON.parse(readFileSync(loansPath, "utf8"))
    const accounts: DeploymentJson = JSON.parse(readFileSync(accountsPath, "utf8"))
    const vault: DeploymentJson = JSON.parse(readFileSync(vaultPath, "utf8"))
    const shortName = `${name}-latest`
    const startBlock = Math.min(loans.blockNumber, accounts.blockNumber, vault.blockNumber)

    usedChains.add(config.chain)
    found.push(name)

    let chainRef = config.chain
    if (config.blockExplorerUrl) {
      const varName = `_${shortName.replace(/-/g, "_")}_chain`
      chainOverrides.push(
        `const ${varName} = { ...${config.chain}, blockExplorers: { default: { ...${config.chain}.blockExplorers!.default, url: '${config.blockExplorerUrl}' } } } as unknown as typeof ${config.chain};`,
      )
      chainRef = varName
    }

    entries.push(`  '${shortName}': {
    id: ${config.deploymentId},
    shortName: '${shortName}',
    startBlock: ${startBlock},
    chain: ${chainRef},
    version: '${loans.version}',
    contracts: {
      Currency: '${loans.contracts.USDC}',
      Loans: '${loans.contracts.Loans}',
      LoansNFT: '${loans.contracts.LoansNFT}',
      LoansExchange: ${addr(loans.contracts.LoansExchange)},
      SafeSingleton: '${accounts.contracts.SafeSingleton}',
      SafeProxyFactory: '${accounts.contracts.SafeProxyFactory}',
      SmartAccountFactory: '${accounts.contracts.SmartAccountFactory}',
      MultiSendCallOnly: '${accounts.contracts.MultiSendCallOnly}',
      TrustedSpender: '${accounts.contracts.TrustedSpender}',
      TrustedCalls: '${accounts.contracts.TrustedCalls}',
      HotSafe: ${addr(loans.contracts.HotSafe)},
      PortfolioVault: '${vault.contracts.PortfolioVault}',
      NavCalculator: '${vault.contracts.NavCalculator}',
      VaultShareToken: '${vault.contracts.VaultShareToken}',
    },
  },\n`)
  }

  if (entries.length === 0) {
    throw new Error("No complete deployments found")
  }

  const chainImports = [...usedChains].sort()

  const code = `// Auto-generated file. Do not edit manually.
// Generated by cli (generate-deployments)

import { ${chainImports.join(", ")} } from 'viem/chains';

export const deployedChains = [
  ${chainImports.join(",\n  ")},
] as const;

export type Chain = (typeof deployedChains)[number];

export const deployedChainIds = deployedChains.map(({ id }) => id);

export type ChainId = (typeof deployedChainIds)[number];

export type Deployment = {
  id: number;
  shortName: string;
  startBlock: number;
  chain: Chain;
  version: string;
  contracts: {
    Currency: \`0x\${string}\`;
    Loans: \`0x\${string}\`;
    LoansNFT: \`0x\${string}\`;
    LoansExchange: \`0x\${string}\` | null;
    SafeSingleton: \`0x\${string}\`;
    SafeProxyFactory: \`0x\${string}\`;
    SmartAccountFactory: \`0x\${string}\`;
    MultiSendCallOnly: \`0x\${string}\`;
    TrustedSpender: \`0x\${string}\`;
    TrustedCalls: \`0x\${string}\`;
    HotSafe: \`0x\${string}\` | null;
    PortfolioVault: \`0x\${string}\`;
    NavCalculator: \`0x\${string}\`;
    VaultShareToken: \`0x\${string}\`;
  };
};
${chainOverrides.length > 0 ? "\n" + chainOverrides.join("\n") + "\n" : ""}
export const deployments = {
${entries.join("")}} as const satisfies Record<string, Deployment>;
`

  const outputPath = resolve(root, "src/deployments.ts")
  writeFileSync(outputPath, code)
  console.log(`Generated ${outputPath}`)
  console.log(`  ${found.length} deployment(s): ${found.join(", ")}`)
  console.log(`  ${chainImports.length} chain(s): ${chainImports.join(", ")}`)
}
