import { readFileSync } from "fs"
import { dirname, resolve } from "path"
import { fileURLToPath } from "url"

/**
 * Pre-baked Anvil dev state shipped with this package.
 *
 * `state/anvil-state.json.gz` is the gzipped `anvil_dumpState` output of a full
 * local deployment rehearsing the production topology: all contracts with the
 * Timelock as guardian and a stand-in Admin Safe as admin, the eight role smart
 * accounts fully configured (originator approval, address book, USDC approvals,
 * TrustedSpender allowances, vault role grants), minted balances, and a seeded
 * vault NAV. Generated by `cli/bake-anvil-state.ts` during the package build.
 */

export interface AnvilManifest {
  /** Package version the snapshot was baked for. */
  version: string
  /** Dev smart-account addresses baked into the snapshot. */
  accounts: {
    Borrower: `0x${string}`
    Investor: `0x${string}`
    Originator: `0x${string}`
    Servicer: `0x${string}`
    Shareholder: `0x${string}`
    PortfolioManager: `0x${string}`
    InvestorManager: `0x${string}`
    CalculatingAgent: `0x${string}`
  }
  /** Environment values consumers previously derived at deploy time. */
  env: {
    HOT_PROXY_SAFE_ADDRESS: `0x${string}`
    TIMELOCK_ADDRESS: `0x${string}`
    ADMIN_SAFE_ADDRESS: `0x${string}`
    PROPOSER_SAFE_ADDRESS: `0x${string}`
    WHITELISTER_SAFE_ADDRESS: `0x${string}`
    OPS_MGMT_SAFE_ADDRESS: `0x${string}`
  }
}

// Works in both output formats: __dirname exists in the CJS bundle; the ESM
// bundle falls back to import.meta.url (esbuild's CJS shim never runs).
function packageRoot(): string {
  if (typeof __dirname !== "undefined") return resolve(__dirname, "..")
  return resolve(dirname(fileURLToPath(import.meta.url)), "..")
}

/**
 * Absolute path to the gzipped Anvil state snapshot.
 *
 * `anvil --load-state` only reads plain JSON, so gunzip the file first, then
 * start anvil with the decompressed copy.
 */
export const stateFilePath: string = resolve(packageRoot(), "state", "anvil-state.json.gz")

const manifest: AnvilManifest = JSON.parse(readFileSync(resolve(packageRoot(), "state", "anvil-manifest.json"), "utf8"))

/** Package version the snapshot was baked for (tracks the contracts version). */
export const version: string = manifest.version

/** Dev smart-account addresses baked into the snapshot. */
export const accounts: AnvilManifest["accounts"] = manifest.accounts

/** Environment values for consumers (HotSafe address etc.). */
export const env: AnvilManifest["env"] = manifest.env
